# Checks for merge conflicts when a pull request is opened or updated
name: Check mergability onto main

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This is important to fetch all history

      - name: Check for merge conflicts
        run: |
          # Fetch the main branch
          git fetch origin main:main

          # Try to merge main onto the current branch
          # The --no-commit and --no-ff flags make sure we don't actually
          # commit a merge or create a merge commit, respectively.
          MERGE_OUTPUT=$(git merge --no-commit --no-ff main) || true

          # Check if there was a merge conflict
          if [[ "${MERGE_OUTPUT}" == *"Automatic merge failed"* ]]; then
            echo "Merge conflict detected. Failing the job..."
            exit 1
          else
            echo "No merge conflicts detected."
            exit 0
          fi

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}